# Generated by Django 3.1.2 on 2020-10-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
